project_id = "lovzfxppnxictkvymyot"

[functions.search-places]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-arrival-notification]
verify_jwt = false